---
title: "BIGSSS Survey 2023"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  html_document:
    toc: yes
    code_folding: hide
    toc_float:
      collapsed: yes
      smooth_scroll: no
      number_sections: yes
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: console
---

# Setup

```{r setup,echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE,cache = F)
options(scipen=9999) # desactivar notacion cientifica
```

```{css, echo=FALSE}
# /* expandir el espacio del documento*/
body .main-container {
      max-width: 1600px !important;
      width: 1600px !important;
    }   

#/* expandir width de la TOC*/
div.tocify {
    width: 22% !important;
    max-width: 331px !important;
    max-height: 102% !important;   
}
```


```{r,echo=FALSE}
# set1 <-  RColorBrewer::brewer.pal(n = 4, name = "Blues")
set1 <- c("#5586B4","#D30132","#999999","#004481","#1C2747")    
options(ggplot2.discrete.fill = set1) 
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_minimal())   
ggplot2::theme_update(text=ggplot2::element_text(family="serif"))        
```

```{r,fig.dim=c(10,4),echo=FALSE}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(tidyverse,haven,sjlabelled,sjmisc,likert)
load(here::here("input/data/proc/bigsss_2023.RData"))
        

df2[df2==-999] <- NA   
df2<- set_na(df2,na = -999)
varlab <- sjlabelled::get_label(df2)
labels <- c("Strongly disagree","Disagree","Neutral","Agree","Strongly agree")

for (i in names(select(df2,v10:v32,v35:v45,v47:v55,v57:v61,v63:v68))) {
  df2[[i]] <- factor(df2[[i]],levels =labels,labels = labels)
}
  
sjlabelled::set_label(df2) <- varlab  

data <- 
frq(df2$v7) %>% 
  as.data.frame() %>% 
  select(category=val,count=frq) %>% 
  na.omit()

# Compute percentages
data$fraction <- data$count / sum(data$count)

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(scales::percent(data$fraction))
# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() +
  geom_text( x=2, aes(y=labelPosition, label=label, color=category), size=5) + # x here controls label position (inner / outer)
  # scale_fill_brewer(palette=3) +
  # scale_color_brewer(palette=3) +
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "right",legend.title=element_blank())+
  labs(title = "Are you an international fellow?",
       subtitle = paste0("n = ",sum(data$count)))      
```

```{r,fig.dim=c(10,5),echo=FALSE}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(tidyverse,haven,sjlabelled,sjmisc,likert)
load(here::here("input/data/proc/bigsss_2023.RData"))

df2[df2==-999] <- NA    
df2<- set_na(df2,na = -999)

varlab <- sjlabelled::get_label(df2)
labels <- c("Strongly disagree","Disagree","Neutral","Agree","Strongly agree")

for (i in names(select(df2,v10:v32,v35:v45,v47:v55,v57:v61,v63:v68))) {
  df2[[i]] <- factor(df2[[i]],levels =labels,labels = labels)
}   

sjlabelled::set_label(df2) <- varlab

data <- 
frq(df2$v8) %>% 
  as.data.frame() %>% 
  select(category=val,count=frq) %>% 
  na.omit()
   
# Compute percentages
data$fraction <- data$count / sum(data$count)

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(scales::percent(data$fraction))
# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() +
  geom_text( x=2, aes(y=labelPosition, label=label, color=category), size=5) + # x here controls label position (inner / outer)
  # scale_fill_brewer(palette=3) +
  # scale_color_brewer(palette=3) +
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "right",legend.title=element_blank())+
  labs(title = "What is your status of affiliation with BIGSS?",
       subtitle = paste0("n = ",sum(data$count)))
```

```{r,fig.dim=c(8,4),echo=FALSE}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(tidyverse,haven,sjlabelled,sjmisc,likert)
load(here::here("input/data/proc/bigsss_2023.RData"))

df2[df2==-999] <- NA 
df2<- set_na(df2,na = -999)

varlab <- sjlabelled::get_label(df2)
labels <- c("Strongly disagree","Disagree","Neutral","Agree","Strongly agree")

for (i in names(select(df2,v10:v32,v35:v45,v47:v55,v57:v61,v63:v68))) {
  df2[[i]] <- factor(df2[[i]],levels =labels,labels = labels)
}

sjlabelled::set_label(df2) <- varlab

data <- 
frq(df2$v9) %>% 
  as.data.frame() %>% 
  select(category=val,count=frq) %>% 
  na.omit()

# Compute percentages
data$fraction <- data$count / sum(data$count)

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(scales::percent(data$fraction))
# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() +
  geom_text( x=2, aes(y=labelPosition, label=label, color=category), size=5) + # x here controls label position (inner / outer)
  # scale_fill_brewer(palette=3) +
  # scale_color_brewer(palette=3) +
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "right",legend.title=element_blank())+
  labs(title = "When did you join BIGSSS?", subtitle = paste0("n = ",sum(data$count)))
```

```{r,fig.dim=c(14,6.5),echo=FALSE}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(tidyverse,haven,sjlabelled,sjmisc,likert,plyr)
load(here::here("input/data/proc/bigsss_2023.RData"))

df2[df2==-999] <- NA 
df2<- set_na(df2,na = -999)

varlab <- sjlabelled::get_label(df2)
labels <- c("Strongly disagree","Disagree","Neutral","Agree","Strongly agree")

for (i in names(select(df2,v10:v32,v35:v45,v47:v55,v57:v61,v63:v68))) {
  df2[[i]] <- factor(df2[[i]],levels =labels,labels = labels)
}

ggplot2::theme_update(text=element_text(size=18,  family="serif"))  
#bigsss color palette
set1 <- c("#5586B4","#D30132","#999999","#004481","#1C2747")

sjlabelled::set_label(df2) <- paste0(varlab, " (n = ",summarise_all(df2,~ sum(!is.na(.))),")")

df_lik1<- df2 
df_lik1 %>% 
  select(v10,v11,v12) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',center=3, wrap=30,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=3) +
  labs(title = "Preparatory Forum") 

df_lik1 %>% 
  select(v13:v15) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',center=3, wrap=35,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Proposal Workshop")

df_lik1 %>% 
  select(v16:v18) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',center=3, wrap=30,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Core Theory Seminar")

df_lik1 %>% 
  select(v19:v21) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',center=3, wrap=30,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Methods Courses")

df_lik1 %>% 
  select(v22,v23,v24) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',center=3, wrap=35,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Doctoral Colloquia")

df_lik1 %>% 
  select(v25,v26,v27) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',center=3, wrap=30,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Lecture Series")

df_lik1 %>% 
  select(v28,v29,v30) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',center=3, wrap=30,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Transferable Skills Workshops")

df_lik1 %>% 
  select(v31,v32) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',center=3, wrap=40,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Progress Assessment Colloquia (PACs)")

df_lik1 %>% 
  select(v33) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',wrap=30,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "BIGSSS Curriculum Overall")


df_lik1 %>% 
  select(v35:v43) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',wrap=40,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Dissertation Committee")

df_lik1 %>% 
  select(v44:v45) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',wrap=40,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "BIGSSS Faculty")

df_lik1 %>% 
  select(v47:v55) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',wrap=40,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Administrative Structures at BIGSSS")

df_lik1 %>% 
  select(v57:v61) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',wrap=40,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Equality, Diversity, and Inclusion at BIGSSS")

df_lik1 %>% 
  select(v57:v61) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',wrap=40,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "Equality, Diversity, and Inclusion at BIGSSS")


df_lik1 %>% 
  select(v63:v68) %>% 
  setNames(get_label(.)) %>% 
  likert() %>%
  plot(low.color="#D95F02",high.color='#1C9E77',wrap=40,plot.percents=TRUE, plot.percent.low=FALSE, plot.percent.high=FALSE, plot.percent.neutral=FALSE,text.size=4)+
  labs(title = "BIGSSS in General")
```

```{r,fig.dim=c(21,8),echo=FALSE}

levels_v70 <- 
c("Contacts with BIGSSS fellows or faculty",
"Funding (e.g., scholarship)",
"Academic excellence in the social sciences",
"Structured doctoral curriculum",
"Freedom to pursue your own research project",
"Close supervision through a doctoral committee",
"The opportunity to work interdisciplinarily",
"The international character of BIGSSS",
"Being part of a cohort of other PhD students",
"Wanted to live in Germany and/or Bremen, specifically",
"It was required for your job",
"Good working conditions (e.g., a work contract)")

labelsv70 <- paste0(c("A","B","C","D",
                      "E","F","G","H",
                      "I","J","K","L"),". ",levels_v70)

levels(df_lik1$v70_1) <- labelsv70
levels(df_lik1$v70_2) <- labelsv70
levels(df_lik1$v70_3) <- labelsv70
df_lik1 %>%
  select(v70_1, v70_2, v70_3) %>%
  setNames(get_label(.)) %>%
  likert() %>%
  plot(
    low.color = "#D95F02",
    high.color = '#1C9E77',
    wrap = 40,
    plot.percents = TRUE,
    plot.percent.low = FALSE,
    plot.percent.high = FALSE,
    plot.percent.neutral = FALSE,
    text.size = 4
  ) +
  labs(title = "Most Important Aspects in Pursuing a PhD at BIGSSS") +
  scale_x_discrete(
    labels = function(x)
      str_wrap(x, width = 40),
    limits = c(
      "Most important behind decision PhD at BIGSSS: Third mention (n = 29)",
      "Most important behind decision PhD at BIGSSS: Second mention (n = 30)",
      "Most important behind decision PhD at BIGSSS: First mention (n = 32)"
    )
  ) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(size = 12),
    axis.text.y =  element_text(size = 22),
    legend.title = element_blank(),
    title = element_text(size = 22)
  )
```



